import Foundation

/// Generates `Bundle+Module.swift` files for targets with resources.
///
/// Called from `FrameworkModule.init` and `App.project` during manifest evaluation
/// to provide a `Bundle.module` accessor identical to the one SPM auto-generates.
/// Only writes files when the target has resources.
/// Follows the same manifest-time side-effect pattern as `PackageSwiftGenerator`.
enum BundleAccessorGenerator {
	static func generate(directory: String, fileSystem: ModuleFileSystem) {
		if fileSystem.hasResources {
			writeAccessor(to: "\(workspaceRoot)/\(directory)/Sources/Generated")
		}

		if fileSystem.hasSharedResources || fileSystem.hasSharedFixtures {
			writeAccessor(to: "\(workspaceRoot)/\(directory)/Tests/Shared/Generated")
		}
	}

	/// Generates `Bundle+Module.swift` at the given path relative to the workspace root.
	static func generateAt(relativePath: String) {
		writeAccessor(to: "\(workspaceRoot)/\(relativePath)")
	}

	/// Removes `Bundle+Module.swift` files previously generated by the Framework strategy.
	///
	/// Called from `SPMModule.init` to prevent duplicate symbols — SPM auto-generates
	/// its own `Bundle.module` accessor, so manual files must be cleaned up.
	static func clean(directory: String, fileSystem: ModuleFileSystem) {
		if fileSystem.hasResources {
			removeAccessor(at: "\(workspaceRoot)/\(directory)/Sources/Generated")
		}

		if fileSystem.hasSharedResources || fileSystem.hasSharedFixtures {
			removeAccessor(at: "\(workspaceRoot)/\(directory)/Tests/Shared/Generated")
		}
	}
}

// MARK: - Private

private extension BundleAccessorGenerator {
	static let content = """
		import Foundation

		private class BundleFinder {}

		extension Foundation.Bundle {
			static let module = Bundle(for: BundleFinder.self)
		}

		"""

	static func writeAccessor(to directoryPath: String) {
		let fileManager = FileManager.default

		if !fileManager.fileExists(atPath: directoryPath) {
			do {
				try fileManager.createDirectory(atPath: directoryPath, withIntermediateDirectories: true)
			} catch {
				fatalError("Failed to create directory at \(directoryPath): \(error)")
			}
		}

		let filePath = "\(directoryPath)/Bundle+Module.swift"
		do {
			try content.write(toFile: filePath, atomically: true, encoding: .utf8)
		} catch {
			fatalError("Failed to write Bundle+Module.swift at \(filePath): \(error)")
		}
	}

	static func removeAccessor(at directoryPath: String) {
		let fileManager = FileManager.default
		let filePath = "\(directoryPath)/Bundle+Module.swift"

		guard fileManager.fileExists(atPath: filePath) else { return }

		do {
			try fileManager.removeItem(atPath: filePath)
		} catch {
			fatalError("Failed to remove Bundle+Module.swift at \(filePath): \(error)")
		}

		// Remove the Generated directory if empty
		if let contents = try? fileManager.contentsOfDirectory(atPath: directoryPath), contents.isEmpty {
			try? fileManager.removeItem(atPath: directoryPath)
		}
	}
}
