name: Setup Environment
description: Install tools, resolve dependencies, generate project, and boot simulator

inputs:
  device:
    description: Simulator device name
    required: false
    default: iPhone 17 Pro
  derived-data-prefix:
    description: Cache key prefix for DerivedData (e.g., unit, ui)
    required: true

runs:
  using: composite
  steps:
    - name: Select Xcode 26.1.1
      shell: bash
      run: |
        sudo xcode-select -s /Applications/Xcode_26.1.1.app
        xcodebuild -version

    - name: Install mise tools
      uses: jdx/mise-action@v2
      with:
        cache: true

    - name: Cache Tuist and SPM dependencies
      uses: actions/cache@v4
      with:
        path: |
          Tuist/.build
          Derived/
        key: tuist-${{ runner.os }}-${{ hashFiles('Tuist/Package.resolved') }}
        restore-keys: |
          tuist-${{ runner.os }}-

    - name: Cache DerivedData
      uses: actions/cache@v4
      with:
        path: derived_data
        key: derived-data-${{ inputs.derived-data-prefix }}-${{ runner.os }}-${{ hashFiles('**/Project.swift', 'Tuist/Package.resolved') }}-${{ github.sha }}
        restore-keys: |
          derived-data-${{ inputs.derived-data-prefix }}-${{ runner.os }}-${{ hashFiles('**/Project.swift', 'Tuist/Package.resolved') }}-
          derived-data-${{ inputs.derived-data-prefix }}-${{ runner.os }}-

    - name: Install SPM dependencies
      shell: bash
      run: mise x -- tuist install

    - name: Generate Xcode project
      shell: bash
      run: mise x -- tuist generate

    - name: Prepare simulator
      shell: bash
      run: |
        xcrun simctl shutdown all
        DEVICE_UDID=$(xcrun simctl list devices available -j | python3 -c "
        import json, sys
        data = json.load(sys.stdin)
        for runtime, devices in data['devices'].items():
            for d in devices:
                if d['name'] == '${{ inputs.device }}' and d['isAvailable']:
                    print(d['udid'])
                    sys.exit(0)
        ")
        if [ -n "$DEVICE_UDID" ]; then
          echo "Booting simulator: $DEVICE_UDID"
          xcrun simctl boot "$DEVICE_UDID"
          echo "Waiting for simulator to be ready..."
          xcrun simctl bootstatus "$DEVICE_UDID" -b
          sleep 3
        else
          echo "Warning: Target simulator not found, will rely on Tuist to create it"
        fi
