# SwiftLint Configuration
# Rules aligned with CLAUDE.md and docs/StyleGuide.md

# Paths to include
included:
  - App
  - Libraries

# Paths to exclude
excluded:
  - Tuist
  - Derived
  - DerivedData
  - build
  - .build
  - "**/.build"
  - "**/Package.swift"

# MARK: - Enabled Rules

opt_in_rules:
  # Idiomatic
  - anonymous_argument_in_multiline_closure
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_self
  - redundant_type_annotation
  - return_value_from_void_function
  - self_binding
  - shorthand_optional_binding
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# MARK: - Disabled Rules

disabled_rules:
  - todo
  - trailing_whitespace

# MARK: - Rule Configuration

# Line length: 140 characters (warning), 200 (error)
line_length:
  warning: 140
  error: 200
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true

# File length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Type body length
type_body_length:
  warning: 300
  error: 500

# Function body length
function_body_length:
  warning: 50
  error: 100

# Function parameter count
function_parameter_count:
  warning: 6
  error: 8

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

# Type name
type_name:
  min_length: 3
  max_length: 50
  allowed_symbols: []
  validates_start_with_lowercase: error

# Identifier name
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  allowed_symbols: ["_"]
  validates_start_with_lowercase: error
  excluded:
    - id
    - ok
    - or
    - io
    - x
    - y
    - z
    - i
    - j
    - k

# Large tuple
large_tuple:
  warning: 3
  error: 4

# Nesting
nesting:
  type_level: 2
  function_level: 3

# Trailing comma: not used
trailing_comma:
  mandatory_comma: false

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 1

# Implicit return
implicit_return:
  included:
    - closure
    - function
    - getter
    - subscript

# Multiline arguments
multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

# Modifier order (uses default order: override before other modifiers)
modifier_order:
  severity: warning

# Sorted imports
sorted_imports:
  severity: warning

# Self binding (use 'self' not 'strongSelf')
self_binding:
  bind_identifier: self

# Closure body length
closure_body_length:
  warning: 30
  error: 50

# Enum case associated values count
enum_case_associated_values_count:
  warning: 4
  error: 6

# MARK: - Custom Rules

custom_rules:
  # Protocol names must end with Contract
  protocol_contract_suffix:
    name: "Protocol Contract Suffix"
    regex: "^protocol\\s+(?!.*Contract\\s*[:{])[A-Z][a-zA-Z0-9]*\\s*[:{]"
    message: "Protocol names must end with 'Contract' suffix"
    severity: warning
    match_kinds:
      - keyword
      - identifier

  # Mock classes must end with Mock
  mock_suffix:
    name: "Mock Suffix"
    regex: "class\\s+(?!.*Mock)[A-Z][a-zA-Z0-9]*Mock[a-zA-Z]+\\s*[:{]"
    message: "Mock class names must end with 'Mock' suffix"
    severity: warning
    match_kinds:
      - keyword
      - identifier

  # No DispatchQueue (use async/await)
  no_dispatch_queue:
    name: "No DispatchQueue"
    regex: "DispatchQueue\\.(main|global)"
    message: "Use async/await instead of DispatchQueue"
    severity: error
    match_kinds:
      - identifier

  # No completion handlers (use async/await)
  no_completion_handler:
    name: "No Completion Handler"
    regex: "completion\\s*:\\s*@escaping"
    message: "Use async/await instead of completion handlers"
    severity: warning
    match_kinds:
      - identifier
      - keyword

  # No Mock prefix (Mock must only be used as suffix)
  no_mock_prefix:
    name: "No Mock Prefix"
    regex: "(class|struct|enum|actor)\\s+Mock[A-Z][a-zA-Z0-9]*|(let|var)\\s+mock[A-Z][a-zA-Z0-9]*"
    message: "'Mock' must only be used as a suffix, not a prefix (e.g., use 'userMock' instead of 'mockUser')"
    severity: error
    match_kinds:
      - keyword
      - identifier
