import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
	name: mainApp.name,
	projects: ["."],
	generationOptions: .options(
		autogeneratedWorkspaceSchemes: .enabled(
			codeCoverageMode: mainApp.coverageMode,
			testingOptions: []
		)
	)
)
