import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
	name: appName,
	projects: ["."] + Modules.projectPaths,
	schemes: AppScheme.allSchemes() + [AppScheme.uiTestsScheme()],
	generationOptions: .options(
		autogeneratedWorkspaceSchemes: .enabled(
			codeCoverageMode: .targets(App.codeCoverageTargets),
			testingOptions: []
		)
	)
)
