import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
	name: appName,
	projects: [
		".",
		CoreModule.path,
	],
	generationOptions: .options(
		autogeneratedWorkspaceSchemes: .enabled(
			codeCoverageMode: .targets(Modules.codeCoverageTargets),
			testingOptions: []
		)
	)
)
