import ProjectDescription

/// Unified aggregation logic for heterogeneous module collections.
///
/// Detects whether the module set contains SPM packages and selects the
/// appropriate aggregation strategy:
/// - **All Framework**: uses `.targets(...)` with explicit testable targets.
/// - **Mixed or all SPM**: uses `.testPlans(...)` with an auto-generated test plan.
enum ModuleAggregation {
	/// Generates a test action for the aggregate Dev scheme.
	///
	/// When all modules are frameworks, uses `.targets(...)` for direct xcodebuild compatibility.
	/// When any module is an SPM package, generates a test plan that supports mixed container paths.
	static func aggregateTestAction(
		modules: [any ModuleContract],
		appTargetReference: TargetReference,
		config: ProjectConfig = projectConfig
	) -> TestAction {
		let hasSPMModules = modules.contains { $0.packageReference != nil }

		if hasSPMModules {
			let testPlanName = TestPlanGenerator.generate(
				appName: config.appName,
				modules: modules
			)
			return .testPlans([.path(testPlanName)])
		} else {
			let testableTargets = modules.flatMap(\.testableTargets)
			let codeCoverageTargets: [TargetReference] = [appTargetReference]
				+ modules.flatMap(\.codeCoverageTargets)

			return .targets(
				testableTargets,
				options: .options(
					coverage: true,
					codeCoverageTargets: codeCoverageTargets
				)
			)
		}
	}

	/// Generates coverage mode for workspace autogenerated schemes.
	///
	/// When all modules are frameworks, uses `.targets(...)` for precise source-only coverage.
	/// When any module is an SPM package, uses `.relevant` (test plan handles coverage targets).
	static func aggregateCoverageMode(
		modules: [any ModuleContract],
		appTargetReference: TargetReference
	) -> Workspace.GenerationOptions.AutogeneratedWorkspaceSchemes.CodeCoverageMode {
		let hasSPMModules = modules.contains { $0.packageReference != nil }

		if hasSPMModules {
			return .relevant
		} else {
			let codeCoverageTargets = modules.flatMap(\.codeCoverageTargets)
			return .targets([appTargetReference] + codeCoverageTargets)
		}
	}
}
