import ProjectDescription

/// Unified aggregation logic for module collections.
///
/// Dispatches on ``ModuleStrategy/active`` to produce the test action:
/// - **Framework**: Uses `.targets(...)` with aggregated testable targets and
///   code coverage targets — no file generation side-effect.
/// - **SPM**: Generates a `.xctestplan` via ``TestPlanGenerator`` and uses
///   `.testPlans(...)`, which is the only mechanism to aggregate test targets
///   across SPM local packages.
enum ModuleAggregation {
	/// Generates a test action for the aggregate Dev scheme.
	///
	/// - Framework: Collects `testableTargets` and `codeCoverageTargets` from
	///   each module and returns `.targets(...)`.
	/// - SPM: Generates a test plan via `TestPlanGenerator` and returns
	///   `.testPlans(...)`. The test plan is the default in the scheme, so
	///   `xcodebuild test -scheme "Challenge (Dev)"` picks it up automatically.
	static func aggregateTestAction(
		modules: [any ModuleContract],
		appTargetReference: TargetReference,
		config: ProjectConfig = projectConfig
	) -> TestAction {
		switch ModuleStrategy.active {
		case .framework:
			let allTestableTargets = modules.flatMap(\.testableTargets)
			let allCoverageTargets = [appTargetReference] + modules.flatMap(\.codeCoverageTargets)
			return .targets(
				allTestableTargets,
				options: .options(
					coverage: true,
					codeCoverageTargets: allCoverageTargets
				)
			)
		case .spm:
			let testPlanName = TestPlanGenerator.generate(
				appName: config.appName,
				modules: modules
			)
			return .testPlans([Path(stringLiteral: testPlanName)])
		}
	}

	/// Generates coverage mode for workspace autogenerated schemes.
	///
	/// Uses `.relevant` so coverage is driven by the scheme's
	/// `codeCoverageTargets`, keeping it consistent across strategies.
	static func aggregateCoverageMode(
		modules: [any ModuleContract],
		appTargetReference: TargetReference
	) -> Workspace.GenerationOptions.AutogeneratedWorkspaceSchemes.CodeCoverageMode {
		.relevant
	}
}
