import ProjectDescription

/// Defines how a module integrates into the Tuist project.
///
/// Each concrete implementation represents a different integration strategy:
/// - `SPMModule`: Modules as SPM local packages (each with its own `Package.swift`).
/// - `FrameworkModule`: Modules as framework targets in the root project.
///
/// Both strategies can be mixed in the same project. Each module definition
/// explicitly selects its concrete strategy. New strategies (e.g., `XCFrameworkModule`)
/// conform to this protocol without modifying existing code (Open/Closed Principle).
///
/// **Constraint:** SPM modules cannot depend on Framework modules (SPM resolution
/// cannot see framework targets in the root project). The reverse is valid.
public protocol ModuleContract: Sendable {
	// MARK: - Instance Properties

	/// Module directory relative to the workspace root (e.g., `"Features/Character"`, `"AppKit"`).
	var directory: String { get }

	/// Resolved target name (e.g., `"ChallengeCharacter"`).
	var name: String { get }

	/// Whether the module's source target should be included in code coverage.
	var includeInCoverage: Bool { get }

	/// Framework targets generated by the module. Empty for SPM.
	var targets: [Target] { get }

	/// Per-module schemes generated by the module. Empty for SPM.
	var schemes: [Scheme] { get }

	/// Target dependency for consuming targets.
	/// SPM: `.package(product:)` / Framework: `.target(name:)`
	var targetDependency: TargetDependency { get }

	/// Mocks dependency for consuming targets.
	/// SPM: `.package(product:)` / Framework: `.target(name:)`
	var mocksTargetDependency: TargetDependency { get }

	/// Package reference for SPM strategy. Nil for Framework.
	var packageReference: Package? { get }

	/// Testable targets for the Dev scheme. Empty for SPM.
	var testableTargets: [TestableTarget] { get }

	/// Code coverage target references. Empty for SPM.
	var codeCoverageTargets: [TargetReference] { get }

	/// Per-target build settings for `Tuist/Package.swift`.
	/// SPM: one entry per detected target (source, mocks, tests). Framework: empty.
	var packageTargetSettings: [String: Settings] { get }

	/// Container path for test plan entries.
	/// SPM: `"container:{directory}"`. Framework: `"container:"`.
	var containerPath: String { get }
}
